//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financier.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Financier.Common.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Bank.
        /// </summary>
        public static string a_bank {
            get {
                return ResourceManager.GetString("a_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string accounts {
            get {
                return ResourceManager.GetString("accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string actions {
            get {
                return ResourceManager.GetString("actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expense.
        /// </summary>
        public static string add_expense {
            get {
                return ResourceManager.GetString("add_expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new transaction.
        /// </summary>
        public static string add_new_transaction {
            get {
                return ResourceManager.GetString("add_new_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add row.
        /// </summary>
        public static string add_row {
            get {
                return ResourceManager.GetString("add_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new rule and apply it to all transactions.
        /// </summary>
        public static string add_rule_tooltip {
            get {
                return ResourceManager.GetString("add_rule_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Split-transactions.
        /// </summary>
        public static string add_split_transactions {
            get {
                return ResourceManager.GetString("add_split_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Split-transfers.
        /// </summary>
        public static string add_split_transfers {
            get {
                return ResourceManager.GetString("add_split_transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Template.
        /// </summary>
        public static string add_template {
            get {
                return ResourceManager.GetString("add_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Transfer.
        /// </summary>
        public static string add_transfer {
            get {
                return ResourceManager.GetString("add_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App id.
        /// </summary>
        public static string app_id {
            get {
                return ResourceManager.GetString("app_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financier Desktop.
        /// </summary>
        public static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup done..
        /// </summary>
        public static string backup_done {
            get {
                return ResourceManager.GetString("backup_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blotter.
        /// </summary>
        public static string blotter {
            get {
                return ResourceManager.GetString("blotter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate totals.
        /// </summary>
        public static string calculate_totals {
            get {
                return ResourceManager.GetString("calculate_totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashback.
        /// </summary>
        public static string cashback {
            get {
                return ResourceManager.GetString("cashback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on start?.
        /// </summary>
        public static string check_for_updates_on_start {
            get {
                return ResourceManager.GetString("check_for_updates_on_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string checkForUpdates {
            get {
                return ResourceManager.GetString("checkForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear notes.
        /// </summary>
        public static string clear_notes {
            get {
                return ResourceManager.GetString("clear_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear note for all transactions.
        /// </summary>
        public static string clear_notes_tooltip {
            get {
                return ResourceManager.GetString("clear_notes_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        public static string commission {
            get {
                return ResourceManager.GetString("commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string condition {
            get {
                return ResourceManager.GetString("condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string conditions {
            get {
                return ResourceManager.GetString("conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete transaction?.
        /// </summary>
        public static string confirm_delete_transaction {
            get {
                return ResourceManager.GetString("confirm_delete_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string csv {
            get {
                return ResourceManager.GetString("csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string currencies {
            get {
                return ResourceManager.GetString("currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default backup directory :.
        /// </summary>
        public static string defaultBackupDirectory {
            get {
                return ResourceManager.GetString("defaultBackupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete row.
        /// </summary>
        public static string delete_row {
            get {
                return ResourceManager.GetString("delete_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected row (Del).
        /// </summary>
        public static string delete_row_tooltip {
            get {
                return ResourceManager.GetString("delete_row_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update to {0} v{1}....
        /// </summary>
        public static string downloading_update {
            get {
                return ResourceManager.GetString("downloading_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop .backup file here.
        /// </summary>
        public static string drag_and_drop {
            get {
                return ResourceManager.GetString("drag_and_drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string duplicate {
            get {
                return ResourceManager.GetString("duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamics.
        /// </summary>
        public static string dynamics {
            get {
                return ResourceManager.GetString("dynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities.
        /// </summary>
        public static string entities {
            get {
                return ResourceManager.GetString("entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loaded {0} entities.
        /// </summary>
        public static string entities_loaded {
            get {
                return ResourceManager.GetString("entities_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate.
        /// </summary>
        public static string exchange_rate {
            get {
                return ResourceManager.GetString("exchange_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rates.
        /// </summary>
        public static string exchange_rates {
            get {
                return ResourceManager.GetString("exchange_rates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rates for the specified currencies and date already exist..
        /// </summary>
        public static string exchange_rates_exist {
            get {
                return ResourceManager.GetString("exchange_rates_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rates not updated..
        /// </summary>
        public static string exchange_rates_not_updated {
            get {
                return ResourceManager.GetString("exchange_rates_not_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rates provider not configured..
        /// </summary>
        public static string exchange_rates_provider_not_configured {
            get {
                return ResourceManager.GetString("exchange_rates_provider_not_configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rates updated successfully from {0}..
        /// </summary>
        public static string exchange_rates_updated {
            get {
                return ResourceManager.GetString("exchange_rates_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Account.
        /// </summary>
        public static string from_account {
            get {
                return ResourceManager.GetString("from_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string highlight {
            get {
                return ResourceManager.GetString("highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight text. Yellow - transaction row, green - other numbers.
        /// </summary>
        public static string highlight_tooltip {
            get {
                return ResourceManager.GetString("highlight_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} transactions..
        /// </summary>
        public static string import_result {
            get {
                return ResourceManager.GetString("import_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} transactions. Skipped {1} duplicates..
        /// </summary>
        public static string import_result_with_duplicates {
            get {
                return ResourceManager.GetString("import_result_with_duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        public static string include {
            get {
                return ResourceManager.GetString("include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income / expense for the period.
        /// </summary>
        public static string income_expense_period {
            get {
                return ResourceManager.GetString("income_expense_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string is_active {
            get {
                return ResourceManager.GetString("is_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        public static string is_default {
            get {
                return ResourceManager.GetString("is_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last transaction.
        /// </summary>
        public static string last_transaction {
            get {
                return ResourceManager.GetString("last_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the latest version..
        /// </summary>
        public static string latest_version {
            get {
                return ResourceManager.GetString("latest_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location details.
        /// </summary>
        public static string location_details {
            get {
                return ResourceManager.GetString("location_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string locations {
            get {
                return ResourceManager.GetString("locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCC.
        /// </summary>
        public static string mcc {
            get {
                return ResourceManager.GetString("mcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monobank CSV.
        /// </summary>
        public static string monobank_csv {
            get {
                return ResourceManager.GetString("monobank_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Rule.
        /// </summary>
        public static string new_rule {
            get {
                return ResourceManager.GetString("new_rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next_step {
            get {
                return ResourceManager.GetString("next_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        public static string not_supported {
            get {
                return ResourceManager.GetString("not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open recipes wizard.
        /// </summary>
        public static string open_recipes_wizard {
            get {
                return ResourceManager.GetString("open_recipes_wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Backup.
        /// </summary>
        public static string openBackup {
            get {
                return ResourceManager.GetString("openBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation amount.
        /// </summary>
        public static string operation_amount {
            get {
                return ResourceManager.GetString("operation_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        public static string original {
            get {
                return ResourceManager.GetString("original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string paste {
            get {
                return ResourceManager.GetString("paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste text from clipboard.
        /// </summary>
        public static string paste_tooltip {
            get {
                return ResourceManager.GetString("paste_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payee.
        /// </summary>
        public static string payee {
            get {
                return ResourceManager.GetString("payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payees.
        /// </summary>
        public static string payees {
            get {
                return ResourceManager.GetString("payees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string pdf {
            get {
                return ResourceManager.GetString("pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pireus PDF.
        /// </summary>
        public static string pireus_pdf {
            get {
                return ResourceManager.GetString("pireus_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKO PDF.
        /// </summary>
        public static string pko_pdf {
            get {
                return ResourceManager.GetString("pko_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Category, From/To Account, Location ....
        /// </summary>
        public static string please_select_category_account {
            get {
                return ResourceManager.GetString("please_select_category_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Category, Project....
        /// </summary>
        public static string please_select_category_project {
            get {
                return ResourceManager.GetString("please_select_category_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select transaction with same balance as selected account, otherwise all transactions will be imported.
        /// </summary>
        public static string please_select_transaction {
            get {
                return ResourceManager.GetString("please_select_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privat XLSX.
        /// </summary>
        public static string privat_xlsx {
            get {
                return ResourceManager.GetString("privat_xlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        public static string providers {
            get {
                return ResourceManager.GetString("providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUMB PDF.
        /// </summary>
        public static string pumb_pdf {
            get {
                return ResourceManager.GetString("pumb_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total : {0:F2} Current : {1:F2} Diff : {2:F2}.
        /// </summary>
        public static string reciept_wizard_total_format {
            get {
                return ResourceManager.GetString("reciept_wizard_total_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste recipes text. Make recipes photo and parse text via Google Lens or other OCR. I&apos;ll look for numbers with article symbol..
        /// </summary>
        public static string recipes_instructions_line1 {
            get {
                return ResourceManager.GetString("recipes_instructions_line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: &quot;123.45 A&quot;, &quot;-54,32-A&quot;, &quot;100 Б&quot;, &quot;123.01 a&quot;.
        /// </summary>
        public static string recipes_instructions_line2 {
            get {
                return ResourceManager.GetString("recipes_instructions_line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string rule {
            get {
                return ResourceManager.GetString("rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule details.
        /// </summary>
        public static string rule_details {
            get {
                return ResourceManager.GetString("rule_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string rules {
            get {
                return ResourceManager.GetString("rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as account.
        /// </summary>
        public static string same_as_account {
            get {
                return ResourceManager.GetString("same_as_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as .db.
        /// </summary>
        public static string saveAsDb {
            get {
                return ResourceManager.GetString("saveAsDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Backup.
        /// </summary>
        public static string saveBackup {
            get {
                return ResourceManager.GetString("saveBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved {0}.
        /// </summary>
        public static string saved_message {
            get {
                return ResourceManager.GetString("saved_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select account.
        /// </summary>
        public static string select_account {
            get {
                return ResourceManager.GetString("select_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default directory.
        /// </summary>
        public static string setDefaultDirectory {
            get {
                return ResourceManager.GetString("setDefaultDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file was corrupted and has been reset. Please re-configure exchange rate settings..
        /// </summary>
        public static string settings_corrupted {
            get {
                return ResourceManager.GetString("settings_corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split-transfers with a currency differ from account&apos;s currency are not yet supported.
        /// </summary>
        public static string split_transfers_currency_not_supported {
            get {
                return ResourceManager.GetString("split_transfers_currency_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure.
        /// </summary>
        public static string structure {
            get {
                return ResourceManager.GetString("structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string symbol {
            get {
                return ResourceManager.GetString("symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Account.
        /// </summary>
        public static string to_account {
            get {
                return ResourceManager.GetString("to_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string total_amount {
            get {
                return ResourceManager.GetString("total_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string total_label {
            get {
                return ResourceManager.GetString("total_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string transaction {
            get {
                return ResourceManager.GetString("transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction details.
        /// </summary>
        public static string transaction_details {
            get {
                return ResourceManager.GetString("transaction_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer details.
        /// </summary>
        public static string transfer_details {
            get {
                return ResourceManager.GetString("transfer_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-split amount.
        /// </summary>
        public static string unsplit_amount {
            get {
                return ResourceManager.GetString("unsplit_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is available.
        /// </summary>
        public static string update_available {
            get {
                return ResourceManager.GetString("update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to restart app and apply the update?.
        /// </summary>
        public static string update_available_question {
            get {
                return ResourceManager.GetString("update_available_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is downloaded. App will now restart to apply the update..
        /// </summary>
        public static string update_downloaded {
            get {
                return ResourceManager.GetString("update_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update exchange rates on start?.
        /// </summary>
        public static string update_exchange_rates_on_start {
            get {
                return ResourceManager.GetString("update_exchange_rates_on_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform application update.
        /// </summary>
        public static string update_failed {
            get {
                return ResourceManager.GetString("update_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should happen, if conditions are met?.
        /// </summary>
        public static string what_should_happen {
            get {
                return ResourceManager.GetString("what_should_happen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLSX.
        /// </summary>
        public static string xlsx {
            get {
                return ResourceManager.GetString("xlsx", resourceCulture);
            }
        }
    }
}
