using System.Collections.Generic;

namespace Financier.Desktop.Localization;

public partial class LocalizationManager
{
    private static readonly IReadOnlyDictionary<string, string> EnglishLocalization =
        new Dictionary<string, string>
        {
            [nameof(drag_and_drop)] = "Drop .backup file here",
            [nameof(download)] = "Download",
            [nameof(active)] = "Active",
            [nameof(id)] = "ID",
            [nameof(exchange_rates)] = "Exchange Rates",
            [nameof(rule)] = "Rule",
            [nameof(add)] = "Add",
            [nameof(main)] = "Main",
            [nameof(checkForUpdates)] = "Check for Updates",
            [nameof(general)] = "General",
            [nameof(add_template)] = "Add Template",
            [nameof(add_expense)] = "Add Expense",
            [nameof(add_transfer)] = "Add Transfer",
            [nameof(pko_pdf)] = "PKO PDF",
            [nameof(privat_xlsx)] = "Privat XLSX",
            [nameof(pireus_pdf)] = "Pireus PDF",
            [nameof(pumb_pdf)] = "PUMB PDF",
            [nameof(pdf)] = "PDF",
            [nameof(csv)] = "CSV",
            [nameof(xlsx)] = "XLSX",
            [nameof(monobank_csv)] = "Monobank CSV",
            [nameof(a_bank)] = "A Bank",
            [nameof(import)] = "Import",
            [nameof(rules)] = "Rules",
            [nameof(exit)] = "Exit",
            [nameof(setDefaultDirectory)] = "Set default directory",
            [nameof(defaultBackupDirectory)] = "Default backup directory :",
            [nameof(saveAsDb)] = "Save as .db",
            [nameof(saveBackup)] = "Save Backup",
            [nameof(openBackup)] = "Open Backup",
            [nameof(settings)] = "Settings",
            [nameof(accounts)] = "Accounts",
            [nameof(blotter)] = "Blotter",
            [nameof(currencies)] = "Currencies",
            [nameof(categories)] = "Categories",
            [nameof(projects)] = "Projects",
            [nameof(title)] = "Title",
            [nameof(payee)] = "Payee",
            [nameof(edit)] = "Edit",
            [nameof(delete)] = "Delete",
            [nameof(transaction)] = "Transaction",
            [nameof(locations)] = "Locations",
            [nameof(payees)] = "Payees",
            [nameof(duplicate)] = "Duplicate",
            [nameof(info)] = "Info",
            [nameof(entities)] = "Entities",
            [nameof(address)] = "Address",
            [nameof(name)] = "Name",
            [nameof(project)] = "Project",
            [nameof(transaction_details)] = "Transaction details",
            [nameof(account)] = "Account",
            [nameof(category)] = "Category",
            [nameof(currency)] = "Currency",
            [nameof(same_as_account)] = "Same as account",
            [nameof(unsplit_amount)] = "Un-split amount",
            [nameof(open_recipes_wizard)] = "Open recipes wizard",
            [nameof(add_split_transfers)] = "Add Split-transfers",
            [nameof(add_split_transactions)] = "Add Split-transactions",
            [nameof(location)] = "Location",
            [nameof(note)] = "Note",
            [nameof(save)] = "Save",
            [nameof(cancel)] = "Cancel",
            [nameof(refresh)] = "Refresh",
            [nameof(clear)] = "Clear",
            [nameof(time)] = "Time",
            [nameof(amount)] = "Amount",
            [nameof(balance)] = "Balance",
            [nameof(description)] = "Description",
            [nameof(total_amount)] = "Total Amount",
            [nameof(include)] = "Include",
            [nameof(last_transaction)] = "Last transaction",
            [nameof(symbol)] = "Symbol",
            [nameof(is_default)] = "Is Default",
            [nameof(location_details)] = "Location details",
            [nameof(is_active)] = "Is Active",
            [nameof(rule_details)] = "Rule details",
            [nameof(conditions)] = "Conditions",
            [nameof(actions)] = "Actions",
            [nameof(what_should_happen)] = "What should happen, if conditions are met?",
            [nameof(check_for_updates_on_start)] = "Check for updates on start?",
            [nameof(providers)] = "Providers",
            [nameof(app_id)] = "App id",
            [nameof(update_exchange_rates_on_start)] = "Update exchange rates on start?",
            [nameof(details)] = "Details",
            [nameof(transfer_details)] = "Transfer details",
            [nameof(from_account)] = "From Account",
            [nameof(to_account)] = "To Account",
            [nameof(rate)] = "Rate",
            [nameof(from)] = "From",
            [nameof(to)] = "To",
            [nameof(date)] = "Date",
            [nameof(created)] = "Created",
            [nameof(condition)] = "Condition",
            // Wizard common
            [nameof(back)] = "Back",
            [nameof(finish)] = "Finish",
            [nameof(next_step)] = "Next",
            // MonoWizard Page1
            [nameof(select_account)] = "Select account",
            // MonoWizard Page2
            [nameof(please_select_transaction)] = "Please select transaction with same balance as selected account, otherwise all transactions will be imported",
            [nameof(operation_amount)] = "Operation amount",
            [nameof(exchange_rate)] = "Exchange Rate",
            [nameof(commission)] = "Commission",
            [nameof(cashback)] = "Cashback",
            // MonoWizard Page3
            [nameof(please_select_category_account)] = "Please select Category, From/To Account, Location ...",
            [nameof(new_rule)] = "New Rule",
            [nameof(delete_row)] = "Delete row",
            [nameof(clear_notes)] = "Clear notes",
            [nameof(add_rule_tooltip)] = "Add new rule and apply it to all transactions",
            [nameof(delete_row_tooltip)] = "Delete selected row (Del)",
            [nameof(clear_notes_tooltip)] = "Clear note for all transactions",
            [nameof(mcc)] = "MCC",
            [nameof(original)] = "Original",
            // RecipesWizard Page1
            [nameof(recipes_instructions_line1)] = "Paste recipes text. Make recipes photo and parse text via Google Lens or other OCR. I'll look for numbers with article symbol.",
            [nameof(recipes_instructions_line2)] = " For example: \"123.45 A\", \"-54,32-A\", \"100 Б\", \"123.01 a\"",
            [nameof(paste)] = "Paste",
            [nameof(highlight)] = "Highlight",
            [nameof(paste_tooltip)] = "Paste text from clipboard",
            [nameof(highlight_tooltip)] = "Highlight text. Yellow - transaction row, green - other numbers",
            [nameof(reciept_wizard_total_format)] = " Total : {0:F2} Current : {1:F2} Diff : {2:F2}",
            // RecipesWizard Page2
            [nameof(please_select_category_project)] = "Please select Category, Project...",
            [nameof(total_label)] = "Total",
            [nameof(add_row)] = "Add row",
            [nameof(order)] = "Order",
            [nameof(calculate_totals)] = "Calculate totals",
            [nameof(add_new_transaction)] = "Add new transaction",
            // MainWindow Messages
            [nameof(backup_done)] = "Backup done.",
            [nameof(import_result)] = "Imported {0} transactions.",
            [nameof(import_result_with_duplicates)] = "Imported {0} transactions. Skipped {1} duplicates.",
            [nameof(saved_message)] = "Saved {0}",
            [nameof(latest_version)] = "You are using the latest version.",
            [nameof(update_available)] = "Version {0} is available",
            [nameof(update_available_question)] = "Would you like to restart app and apply the update?",
            [nameof(downloading_update)] = "Downloading update to {0} v{1}...",
            [nameof(update_downloaded)] = "Update is downloaded. App will now restart to apply the update.",
            [nameof(update_failed)] = "Failed to perform application update",
            [nameof(exchange_rates_updated)] = "Exchange rates updated successfully from {0}.",
            [nameof(exchange_rates_exist)] = "Exchange rates for the specified currencies and date already exist.",
            [nameof(exchange_rates_not_updated)] = "Exchange rates not updated.",
            [nameof(exchange_rates_provider_not_configured)] = "Exchange rates provider not configured.",
            [nameof(settings_corrupted)] = "Settings file was corrupted and has been reset. Please re-configure exchange rate settings.",
            [nameof(entities_loaded)] = "Successfully loaded {0} entities",
            // Delete Confirmation Messages
            [nameof(confirm_delete_transaction)] = "Are you sure you want to delete transaction?",
            // Dialog Messages
            [nameof(split_transfers_currency_not_supported)] = "Split-transfers with a currency differ from account's currency are not yet supported",
            [nameof(not_supported)] = "Not supported",
        };
}
