using System.Collections.Generic;

namespace Financier.Desktop.Localization;

public partial class LocalizationManager
{
    private static readonly IReadOnlyDictionary<string, string> PolishLocalization =
        new Dictionary<string, string>
        {
            [nameof(drag_and_drop)] = "Przeciągnij plik .backup tutaj",
            [nameof(download)] = "Pobierz",
            [nameof(active)] = "Aktywny",
            [nameof(id)] = "ID",
            [nameof(exchange_rates)] = "Kursy wymiany",
            [nameof(rule)] = "Reguła",
            [nameof(add)] = "Dodaj",
            [nameof(main)] = "Główna",
            [nameof(checkForUpdates)] = "Sprawdź aktualizacje",
            [nameof(general)] = "Ogólne",
            [nameof(add_template)] = "Dodaj szablon",
            [nameof(add_expense)] = "Dodaj wydatek",
            [nameof(add_transfer)] = "Dodaj transfer",
            [nameof(import)] = "Import",
            [nameof(rules)] = "Reguły",
            [nameof(exit)] = "Wyjście",
            [nameof(setDefaultDirectory)] = "Ustaw katalog domyślny",
            [nameof(defaultBackupDirectory)] = "Katalog kopii zapasowej domyślnie :",
            [nameof(saveAsDb)] = "Zapisz jako .db",
            [nameof(saveBackup)] = "Zapisz kopię zapasową",
            [nameof(openBackup)] = "Otwórz kopię zapasową",
            [nameof(settings)] = "Ustawienia",
            [nameof(accounts)] = "Rachunki",
            [nameof(blotter)] = "Operacje",
            [nameof(currencies)] = "Waluty",
            [nameof(categories)] = "Kategorie",
            [nameof(projects)] = "Projekty",
            [nameof(title)] = "Tytuł",
            [nameof(payee)] = "Odbiorca",
            [nameof(edit)] = "Edytuj",
            [nameof(delete)] = "Usuń",
            [nameof(transaction)] = "Transakcja",
            [nameof(locations)] = "Lokalizacje",
            [nameof(payees)] = "Odbiorcy",
            [nameof(duplicate)] = "Duplikat",
            [nameof(info)] = "Informacje",
            [nameof(entities)] = "Jednostki",
            [nameof(address)] = "Adres",
            [nameof(name)] = "Nazwa",
            [nameof(project)] = "Projekt",
            [nameof(reports)] = "Raporty",
            [nameof(transaction_details)] = "Szczegóły transakcji",
            [nameof(account)] = "Rachunek",
            [nameof(category)] = "Kategoria",
            [nameof(currency)] = "Waluta",
            [nameof(same_as_account)] = "Tak samo jak rachunek",
            [nameof(unsplit_amount)] = "Kwota niezdzielona",
            [nameof(open_recipes_wizard)] = "Otwórz kreatora przepisów",
            [nameof(add_split_transfers)] = "Dodaj podziałowe transfery",
            [nameof(add_split_transactions)] = "Dodaj podziałowe transakcje",
            [nameof(location)] = "Lokalizacja",
            [nameof(note)] = "Notatka",
            [nameof(save)] = "Zapisz",
            [nameof(cancel)] = "Anuluj",
            [nameof(refresh)] = "Odśwież",
            [nameof(clear)] = "Wyczyść",
            [nameof(time)] = "Czas",
            [nameof(amount)] = "Kwota",
            [nameof(balance)] = "Saldo",
            [nameof(description)] = "Opis",
            [nameof(total_amount)] = "Całkowita kwota",
            [nameof(include)] = "Uwzględnij",
            [nameof(last_transaction)] = "Ostatnia transakcja",
            [nameof(symbol)] = "Symbol",
            [nameof(is_default)] = "Domyślny",
            [nameof(location_details)] = "Szczegóły lokalizacji",
            [nameof(is_active)] = "Aktywny",
            [nameof(rule_details)] = "Szczegóły reguły",
            [nameof(conditions)] = "Warunki",
            [nameof(actions)] = "Akcje",
            [nameof(what_should_happen)] = "Co powinno się stać, jeśli warunki są spełnione?",
            [nameof(check_for_updates_on_start)] = "Sprawdzić aktualizacje przy uruchomieniu?",
            [nameof(providers)] = "Dostawcy",
            [nameof(app_id)] = "ID aplikacji",
            [nameof(update_exchange_rates_on_start)] = "Aktualizować kursy wymiany przy uruchomieniu?",
            [nameof(details)] = "Szczegóły",
            [nameof(transfer_details)] = "Szczegóły transferu",
            [nameof(from_account)] = "Z rachunku",
            [nameof(to_account)] = "Na rachunek",
            [nameof(rate)] = "Kurs",
            [nameof(from)] = "Z",
            [nameof(to)] = "Na",
            [nameof(date)] = "Data",
            [nameof(created)] = "Utworzono",
            [nameof(condition)] = "Warunek",
            // Wizard common
            [nameof(back)] = "Wstecz",
            [nameof(finish)] = "Zakończyć",
            [nameof(next_step)] = "Dalej",
            // MonoWizard Page1
            [nameof(select_account)] = "Wybierz rachunek",
            // MonoWizard Page2
            [nameof(please_select_transaction)] = "Proszę wybrać transakcję z tym samym saldem co wybrany rachunek, w przeciwnym razie wszystkie transakcje będą importowane",
            [nameof(operation_amount)] = "Kwota operacji",
            [nameof(exchange_rate)] = "Kurs wymiany",
            [nameof(commission)] = "Prowizja",
            [nameof(cashback)] = "Cashback",
            // MonoWizard Page3
            [nameof(please_select_category_account)] = "Proszę wybrać Kategorię, Z/Na rachunek, Lokalizację ...",
            [nameof(new_rule)] = "Nowa reguła",
            [nameof(delete_row)] = "Usuń wiersz",
            [nameof(clear_notes)] = "Wyczyść notatki",
            [nameof(add_rule_tooltip)] = "Dodaj nową regułę i zastosuj ją do wszystkich transakcji",
            [nameof(delete_row_tooltip)] = "Usuń wybrany wiersz (Del)",
            [nameof(clear_notes_tooltip)] = "Wyczyść notatkę dla wszystkich transakcji",
            [nameof(mcc)] = "MCC",
            [nameof(original)] = "Oryginał",
            // RecipesWizard Page1
            [nameof(recipes_instructions_line1)] = "Wklej tekst przepisu. Zrób zdjęcie przepisu i przeanalizuj tekst za pomocą Google Lens lub innego OCR. Będę szukać liczb z symbolem artykułu.",
            [nameof(recipes_instructions_line2)] = " Na przykład: \"123.45 A\", \"-54,32-A\", \"100 Б\", \"123.01 a\"",
            [nameof(paste)] = "Wklej",
            [nameof(highlight)] = "Wyróżnij",
            [nameof(paste_tooltip)] = "Wklej tekst ze schowka",
            [nameof(highlight_tooltip)] = "Wyróżnij tekst. Żółty - wiersz transakcji, zielony - inne liczby",
            [nameof(reciept_wizard_total_format)] = " Suma : {0:F2} Bieżące : {1:F2} Różnica : {2:F2}",
            // RecipesWizard Page2
            [nameof(please_select_category_project)] = "Proszę wybrać Kategorię, Projekt...",
            [nameof(total_label)] = "Suma",
            [nameof(add_row)] = "Dodaj wiersz",
            [nameof(order)] = "Zamówienie",
            [nameof(calculate_totals)] = "Oblicz sumy",
            [nameof(add_new_transaction)] = "Dodaj nową transakcję",
            // MainWindow Messages
            [nameof(backup_done)] = "Kopia zapasowa wykonana.",
            [nameof(import_result)] = "Zaimportowano {0} transakcji.",
            [nameof(import_result_with_duplicates)] = "Zaimportowano {0} transakcji. Pominięto {1} duplikatów.",
            [nameof(saved_message)] = "Zapisano {0}",
            [nameof(latest_version)] = "Używasz najnowszej wersji.",
            [nameof(update_available)] = "Dostępna wersja {0}",
            [nameof(update_available_question)] = "Czy chcesz ponownie uruchomić aplikację i zastosować aktualizację?",
            [nameof(downloading_update)] = "Pobieranie aktualizacji do {0} v{1}...",
            [nameof(update_downloaded)] = "Aktualizacja została pobrana. Aplikacja zostanie teraz uruchomiona ponownie w celu zastosowania aktualizacji.",
            [nameof(update_failed)] = "Nie powiodło się wykonanie aktualizacji aplikacji",
            [nameof(exchange_rates_updated)] = "Kursy wymiany zostały pomyślnie zaktualizowane od {0}.",
            [nameof(exchange_rates_exist)] = "Kursy wymiany dla podanych walut i daty już istnieją.",
            [nameof(exchange_rates_not_updated)] = "Kursy wymiany nie zostały zaktualizowane.",
            [nameof(exchange_rates_provider_not_configured)] = "Dostawca kursów wymiany nie jest skonfigurowany.",
            [nameof(settings_corrupted)] = "Plik ustawień został uszkodzony i został zresetowany. Proszę ponownie skonfigurować ustawienia kursów wymiany.",
            [nameof(entities_loaded)] = "Pomyślnie załadowano {0} jednostek",
            // Delete Confirmation Messages
            [nameof(confirm_delete_transaction)] = "Czy jesteś pewna, że chcesz usunąć transakcję?",
            // Dialog Messages
            [nameof(split_transfers_currency_not_supported)] = "Podziałowe transfery z walutą różną od waluty rachunku nie są jeszcze obsługiwane",
            [nameof(not_supported)] = "Nie obsługiwane",
            // Reports
            [nameof(income_expense_period)] = "Dochody / wydatki za okres",
            [nameof(structure)] = "Struktura",
            [nameof(dynamics)] = "Dynamika",
        };
}

