using System.Collections.Generic;

namespace Financier.Desktop.Localization;

public partial class LocalizationManager
{
    private static readonly IReadOnlyDictionary<string, string> UkrainianLocalization =
        new Dictionary<string, string>
        {
            [nameof(active)] = "Активний",
            [nameof(id)] = "Ідентифікатор",
            [nameof(download)] = "Завантажити",
            [nameof(exchange_rates)] = "Обмінні курси",
            [nameof(rule)] = "Правило",
            [nameof(add)] = "Додати",
            [nameof(main)] = "Головна",
            [nameof(checkForUpdates)] = "Перевірити оновлення",
            [nameof(general)] = "Загальні",
            [nameof(add_template)] = "Додати шаблон",
            [nameof(add_expense)] = "Додати витрату",
            [nameof(add_transfer)] = "Додати переказ",
            [nameof(privat_xlsx)] = "Приват XLSX",
            [nameof(pireus_pdf)] = "Піреус PDF",
            [nameof(pumb_pdf)] = "ПУМБ PDF",
            [nameof(monobank_csv)] = "Монобанк CSV",
            [nameof(a_bank)] = "А Банк",
            [nameof(import)] = "Імпорт",
            [nameof(rules)] = "Правила",
            [nameof(exit)] = "Вихід",
            [nameof(setDefaultDirectory)] = "Встановити каталог за замовчуванням",
            [nameof(defaultBackupDirectory)] = "Каталог за замовчуванням :",
            [nameof(saveAsDb)] = "Зберегти як .db",
            [nameof(saveBackup)] = "Зберегти резервну копію",
            [nameof(openBackup)] = "Відкрити резервну копію",
            [nameof(settings)] = "Налаштування",
            [nameof(accounts)] = "Рахунки",
            [nameof(blotter)] = "Журнал",
            [nameof(currencies)] = "Валюти",
            [nameof(categories)] = "Категорії",
            [nameof(projects)] = "Проекти",
            [nameof(title)] = "Назва",
            [nameof(payee)] = "Одержувач",
            [nameof(edit)] = "Редагувати",
            [nameof(delete)] = "Видалити",
            [nameof(project)] = "Проект",
            [nameof(reports)] = "Звіти",
            [nameof(locations)] = "Місцезнаходження",
            [nameof(payees)] = "Одержувачі",
            [nameof(duplicate)] = "Дублювати",
            [nameof(info)] = "Інформація",
            [nameof(entities)] = "Сутності",
            [nameof(address)] = "Адреса",
            [nameof(name)] = "Назва",
            [nameof(drag_and_drop)] = "Перетягніть файл .backup сюди",
            [nameof(transaction)] = "Операція",
            [nameof(transaction_details)] = "Деталі операції",
            [nameof(account)] = "Рахунок",
            [nameof(category)] = "Категорія",
            [nameof(currency)] = "Валюта",
            [nameof(same_as_account)] = "Як у рахунку",
            [nameof(unsplit_amount)] = "Невинесена сума",
            [nameof(open_recipes_wizard)] = "Відкрити майстер рецептів",
            [nameof(add_split_transfers)] = "Додати розділені перекази",
            [nameof(add_split_transactions)] = "Додати розділені операції",
            [nameof(location)] = "Місцезнаходження",
            [nameof(note)] = "Примітка",
            [nameof(save)] = "Зберегти",
            [nameof(cancel)] = "Скасувати",
            [nameof(refresh)] = "Оновити",
            [nameof(clear)] = "Очистити",
            [nameof(time)] = "Час",
            [nameof(amount)] = "Сума",
            [nameof(balance)] = "Залишок",
            [nameof(description)] = "Опис",
            [nameof(total_amount)] = "Загальна сума",
            [nameof(include)] = "Включити",
            [nameof(last_transaction)] = "Остання операція",
            [nameof(symbol)] = "Символ",
            [nameof(is_default)] = "За замовчуванням",
            [nameof(location_details)] = "Деталі місцезнаходження",
            [nameof(is_active)] = "Активне",
            [nameof(rule_details)] = "Деталі правила",
            [nameof(conditions)] = "Умови",
            [nameof(actions)] = "Дії",
            [nameof(what_should_happen)] = "Що повинно статися, якщо умови виконані?",
            [nameof(check_for_updates_on_start)] = "Перевірити оновлення при запуску?",
            [nameof(providers)] = "Постачальники",
            [nameof(app_id)] = "ID програми",
            [nameof(update_exchange_rates_on_start)] = "Оновити обмінні курси при запуску?",
            [nameof(details)] = "Деталі",
            [nameof(transfer_details)] = "Деталі переказу",
            [nameof(from_account)] = "З рахунку",
            [nameof(to_account)] = "На рахунок",
            [nameof(rate)] = "Коефіцієнт",
            [nameof(from)] = "З",
            [nameof(to)] = "На",
            [nameof(date)] = "Дата",
            [nameof(created)] = "Створено",
            [nameof(condition)] = "Умова",
            [nameof(back)] = "Назад",
            [nameof(finish)] = "Завершити",
            [nameof(next_step)] = "Далі",
            [nameof(select_account)] = "Виберіть рахунок",
            [nameof(please_select_transaction)] = "Виберіть операцію з таким же залишком як вибраний рахунок, інакше будуть імпортовані всі операції",
            [nameof(operation_amount)] = "Сума операції",
            [nameof(exchange_rate)] = "Обмінний курс",
            [nameof(commission)] = "Комісія",
            [nameof(cashback)] = "Кешбек",
            [nameof(please_select_category_account)] = "Виберіть Категорію, З/На рахунок, Місцезнаходження ...",
            [nameof(new_rule)] = "Нове правило",
            [nameof(delete_row)] = "Видалити рядок",
            [nameof(clear_notes)] = "Очистити примітки",
            [nameof(add_rule_tooltip)] = "Додати нове правило та застосувати його до всіх операцій",
            [nameof(delete_row_tooltip)] = "Видалити вибраний рядок (Del)",
            [nameof(clear_notes_tooltip)] = "Очистити примітку для всіх операцій",
            [nameof(mcc)] = "MCC",
            [nameof(original)] = "Оригіналь",
            [nameof(recipes_instructions_line1)] = "Вставте текст рецепту. Зробіть фото рецепту та розберіть текст за допомогою Google Lens чи іншого OCR. Я шукатиму числа з символом товару.",
            [nameof(recipes_instructions_line2)] = " Наприклад: \"123.45 A\", \"-54,32-A\", \"100 Б\", \"123.01 a\"",
            [nameof(paste)] = "Вставити",
            [nameof(highlight)] = "Виділити",
            [nameof(paste_tooltip)] = "Вставити текст з буфера обміну",
            [nameof(highlight_tooltip)] = "Виділити текст. Жовтий - рядок операції, зелений - інші числа",
            [nameof(please_select_category_project)] = "Виберіть Категорію, Проект...",
            [nameof(total_label)] = "Всього",
            [nameof(add_row)] = "Додати рядок",
            [nameof(order)] = "Замовлення",
            [nameof(calculate_totals)] = "Обчислити загальні суми",
            [nameof(add_new_transaction)] = "Додати нову операцію",
            // RecipesWizard Page1
            [nameof(reciept_wizard_total_format)] = "Всього : {0:F2} Поточне : {1:F2} Різниця : {2:F2}",
            // MainWindow Messages
            [nameof(backup_done)] = "Резервну копію збережено.",
            [nameof(import_result)] = "Імпортовано {0} операцій.",
            [nameof(import_result_with_duplicates)] = "Імпортовано {0} операцій. Пропущено {1} дублікатів.",
            [nameof(saved_message)] = "Збережено {0}",
            [nameof(latest_version)] = "Ви використовуєте найновішу версію.",
            [nameof(update_available)] = "Доступна версія {0}",
            [nameof(update_available_question)] = "Ви хочете перезагрузити програму та застосувати оновлення?",
            [nameof(downloading_update)] = "Завантажуємо оновлення до {0} v{1}...",
            [nameof(update_downloaded)] = "Оновлення завантажено. Програма зараз перезагрузиться для застосування оновлення.",
            [nameof(update_failed)] = "Не вдалося виконати оновлення програми",
            [nameof(exchange_rates_updated)] = "Обмінні курси успішно оновлені від {0}.",
            [nameof(exchange_rates_exist)] = "Обмінні курси для вказаних валют та дати вже існують.",
            [nameof(exchange_rates_not_updated)] = "Обмінні курси не оновлені.",
            [nameof(exchange_rates_provider_not_configured)] = "Постачальник обмінних курсів не налаштований.",
            [nameof(settings_corrupted)] = "Файл налаштувань був пошкоджений і скинутий до замовчуванням. Будь ласка, перенастройте налаштування обмінних курсів.",
            [nameof(entities_loaded)] = "Успішно завантажено {0} сутностей",
            // Delete Confirmation Messages
            [nameof(confirm_delete_transaction)] = "Ви впевнені, що хочете видалити операцію?",
            // Dialog Messages
            [nameof(split_transfers_currency_not_supported)] = "Розділені перекази з валютою, яка відрізняється від валюти рахунку, ще не підтримуються",
            [nameof(not_supported)] = "Не підтримується",
        };
}

